name: Execute Osmo Tests and Publish Report

on:
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    env:
      MOBILE_OS: Android
      ANDROID_HOME: /home/runner/Android/Sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
      SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
      APPIUM_FILE_PATH: /usr/local/lib/node_modules/appium/build/lib/main.js
      DEVICE_NAME: pixel_4_xl
      OS_VERSION: 14
      MAIN_ACTIVITY: com.osmo.smt.MainActivity
      APP_PACKAGE: com.osmo.smt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add Android platform-tools to PATH
        run: echo "${ANDROID_HOME}/platform-tools" >> $GITHUB_PATH

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium globally
        run: npm install -g appium

      - name: Verify Appium installation
        run: appium -v

      - name: Enable KVM for hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android emulator and tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_4_xl
          disable-animations: true
          script: mvn test -DsuiteXmlFile=src/test/resources/testng.xml

      - name: Copy reports
        if: always()
        run: |
          mkdir -p out
          cp -r AndroidAutomationReport/* out/
          echo "Contents of 'out' directory after copying reports:"
          ls -lR out/

      - name: Fetch full git history
        if: always()
        run: git fetch --prune --unshallow

      - name: Clean untracked files before checkout
        if: always()
        run: git clean -fdx

      - name: Checkout gh-pages branch
        if: always()
        run: |
          git checkout gh-pages
          git pull origin gh-pages

      - name: Commit and push reports
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A out/
          echo "Git status before commit:"
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add test reports from workflow run $GITHUB_RUN_ID"
            git push origin gh-pages
          fi